-- 00_setup.sql
-- Telecom Funnel Intelligence DB 초기화

CREATE DATABASE IF NOT EXISTS TELECOM_DB;

CREATE SCHEMA IF NOT EXISTS TELECOM_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS TELECOM_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS TELECOM_DB.MART;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE TELECOM_DB;
USE WAREHOUSE COMPUTE_WH;

-- Cortex Analyst 시맨틱 모델 스테이지
CREATE OR REPLACE STAGE TELECOM_DB.PUBLIC.CORTEX_STAGE
    DIRECTORY = (ENABLE = TRUE);

-- Stored Procedure 스테이지
CREATE OR REPLACE STAGE TELECOM_DB.ANALYTICS.SPROC_STAGE;
