-- 01_staging.sql
-- 마켓플레이스 뷰 → STAGING 테이블 (데이터 품질 보정 적용)
-- 실행 순서: 00_setup.sql → 01_staging.sql

USE DATABASE TELECOM_DB;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- STG_FUNNEL: V03 퍼널 전환율 (CVR 클램핑 + NULL 보정 + 미래일자 제외)
-- =========================================================================
CREATE OR REPLACE TABLE STAGING.STG_FUNNEL AS
SELECT
    YEAR_MONTH,
    MAIN_CATEGORY_NAME,
    MAIN_CATEGORY_NAME                       AS CATEGORY,
    COALESCE(TOTAL_COUNT, 0)              AS TOTAL_COUNT,
    COALESCE(CONSULT_REQUEST_COUNT, 0)    AS CONSULT_REQUEST_COUNT,
    COALESCE(SUBSCRIPTION_COUNT, 0)       AS SUBSCRIPTION_COUNT,
    COALESCE(REGISTEND_COUNT, 0)          AS REGISTEND_COUNT,
    COALESCE(OPEN_COUNT, 0)              AS OPEN_COUNT,
    COALESCE(PAYEND_COUNT, 0)            AS PAYEND_COUNT,
    LEAST(COALESCE(CVR_CONSULT_REQUEST, 0), 100.0) AS CVR_CONSULT_REQUEST,
    LEAST(COALESCE(CVR_SUBSCRIPTION, 0), 100.0)    AS CVR_SUBSCRIPTION,
    LEAST(COALESCE(CVR_REGISTEND, 0), 100.0)       AS CVR_REGISTEND,
    LEAST(COALESCE(CVR_OPEN, 0), 100.0)            AS CVR_OPEN,
    LEAST(COALESCE(CVR_PAYEND, 0), 100.0)          AS CVR_PAYEND,
    LEAST(COALESCE(OVERALL_CVR, 0), 100.0)         AS OVERALL_CVR
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V03_CONTRACT_FUNNEL_CONVERSION
WHERE YEAR_MONTH <= CURRENT_DATE();

-- 클러스터링: YEAR_MONTH 기반 필터가 빈번하므로 마이크로 파티셔닝 최적화
ALTER TABLE STAGING.STG_FUNNEL CLUSTER BY (YEAR_MONTH, MAIN_CATEGORY_NAME);

-- =========================================================================
-- STG_CHANNEL: V04 채널별 계약 성과 (NULL 보정 + 미래일자 제외)
-- =========================================================================
CREATE OR REPLACE TABLE STAGING.STG_CHANNEL AS
SELECT
    YEAR_MONTH,
    MAIN_CATEGORY_NAME,
    MAIN_CATEGORY_NAME                AS CATEGORY,
    RECEIVE_PATH_NAME,
    RECEIVE_PATH_NAME                 AS CHANNEL,
    INFLOW_PATH_NAME,
    COALESCE(CONTRACT_COUNT, 0)   AS CONTRACT_COUNT,
    COALESCE(REGISTEND_COUNT, 0)  AS REGISTEND_COUNT,
    COALESCE(OPEN_COUNT, 0)      AS OPEN_COUNT,
    COALESCE(PAYEND_COUNT, 0)    AS PAYEND_COUNT,
    LEAST(COALESCE(OPEN_CVR, 0), 100.0)   AS OPEN_CVR,
    LEAST(COALESCE(PAYEND_CVR, 0), 100.0) AS PAYEND_CVR,
    COALESCE(AVG_NET_SALES, 0)   AS AVG_NET_SALES,
    COALESCE(TOTAL_NET_SALES, 0) AS TOTAL_NET_SALES
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V04_CHANNEL_CONTRACT_PERFORMANCE
WHERE YEAR_MONTH <= CURRENT_DATE();

ALTER TABLE STAGING.STG_CHANNEL CLUSTER BY (YEAR_MONTH, MAIN_CATEGORY_NAME);

-- =========================================================================
-- STG_REGIONAL: V01 지역별 계약 + V05 신규설치 LEFT JOIN
--   전북특별자치도 → 전북 통합, 빈 문자열 제외, 미래일자 제외
-- =========================================================================
CREATE OR REPLACE TABLE STAGING.STG_REGIONAL AS
SELECT
    v01.YEAR_MONTH,
    REPLACE(v01.INSTALL_STATE, '전북특별자치도', '전북') AS INSTALL_STATE,
    v01.INSTALL_CITY,
    v01.MAIN_CATEGORY_NAME,
    COALESCE(v01.CONTRACT_COUNT, 0)        AS CONTRACT_COUNT,
    COALESCE(v01.CONSULT_REQUEST_COUNT, 0) AS CONSULT_REQUEST_COUNT,
    COALESCE(v01.REGISTEND_COUNT, 0)       AS REGISTEND_COUNT,
    COALESCE(v01.OPEN_COUNT, 0)           AS OPEN_COUNT,
    COALESCE(v01.PAYEND_COUNT, 0)         AS PAYEND_COUNT,
    LEAST(COALESCE(v01.REGISTEND_CVR, 0), 100.0) AS REGISTEND_CVR,
    LEAST(COALESCE(v01.OPEN_CVR, 0), 100.0)      AS OPEN_CVR,
    LEAST(COALESCE(v01.PAYEND_CVR, 0), 100.0)    AS PAYEND_CVR,
    COALESCE(v01.AVG_NET_SALES, 0)         AS AVG_NET_SALES,
    COALESCE(v01.TOTAL_NET_SALES, 0)       AS TOTAL_NET_SALES,
    -- V05 신규설치 지표
    COALESCE(v05.CONTRACT_COUNT, 0)  AS NEW_INSTALL_COUNT,
    COALESCE(v05.OPEN_COUNT, 0)     AS NEW_OPEN_COUNT,
    COALESCE(v05.PAYEND_COUNT, 0)   AS NEW_PAYEND_COUNT,
    COALESCE(v05.BUNDLE_COUNT, 0)   AS BUNDLE_COUNT,
    COALESCE(v05.STANDALONE_COUNT, 0) AS STANDALONE_COUNT,
    COALESCE(v05.AVG_NET_SALES, 0)  AS NEW_AVG_NET_SALES
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V01_MONTHLY_REGIONAL_CONTRACT_STATS AS v01
LEFT JOIN SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V05_REGIONAL_NEW_INSTALL AS v05
    ON  v01.YEAR_MONTH = v05.YEAR_MONTH
    AND REPLACE(v01.INSTALL_STATE, '전북특별자치도', '전북')
        = REPLACE(v05.INSTALL_STATE, '전북특별자치도', '전북')
    AND v01.INSTALL_CITY = v05.INSTALL_CITY
WHERE v01.INSTALL_STATE != ''
  AND v01.YEAR_MONTH <= CURRENT_DATE();

ALTER TABLE STAGING.STG_REGIONAL CLUSTER BY (YEAR_MONTH, INSTALL_STATE);

-- =========================================================================
-- STG_MARKETING: V07 GA4 마케팅 어트리뷰션 (15개월 한정 데이터)
-- =========================================================================
CREATE OR REPLACE TABLE STAGING.STG_MARKETING AS
SELECT
    YEAR_MONTH,
    UTM_SOURCE,
    UTM_MEDIUM,
    COALESCE(TOTAL_SESSIONS, 0)          AS TOTAL_SESSIONS,
    COALESCE(TOTAL_USERS, 0)             AS TOTAL_USERS,
    COALESCE(TOTAL_CONSULT_REQUESTS, 0)  AS TOTAL_CONSULT_REQUESTS,
    COALESCE(TOTAL_CONSULT_PHONE, 0)     AS TOTAL_CONSULT_PHONE,
    COALESCE(TOTAL_CONSULT_KAKAO, 0)     AS TOTAL_CONSULT_KAKAO,
    COALESCE(TOTAL_CONSULT_CHANNELTALK, 0) AS TOTAL_CONSULT_CHANNELTALK,
    COALESCE(TOTAL_CONTRACTS, 0)         AS TOTAL_CONTRACTS,
    LEAST(COALESCE(CONSULT_CVR, 0), 100.0)  AS CONSULT_CVR,
    LEAST(COALESCE(CONTRACT_CVR, 0), 100.0) AS CONTRACT_CVR,
    COALESCE(TOTAL_REVENUE, 0)           AS TOTAL_REVENUE
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V07_GA4_MARKETING_ATTRIBUTION
WHERE YEAR_MONTH <= CURRENT_DATE();
