-- 04_cortex_ml.sql
-- Cortex ML: FORECAST + ANOMALY DETECTION
-- 04, 05는 비필수 — 실패해도 파이프라인 계속 진행

USE DATABASE TELECOM_DB;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- 1. (REMOVED) CVR FORECAST — 제거됨
--    CVR은 비율 지표(0~100)라 음수 예측·넓은 CI 발생 → CONTRACT_COUNT만 사용
-- =========================================================================

-- 기존 CVR 예측 데이터 정리
DELETE FROM MART.FORECAST_OUTPUT WHERE TARGET_METRIC = 'OVERALL_CVR';

-- =========================================================================
-- 2. ANOMALY DETECTION: 시도별 CONTRACT_COUNT 이상치 탐지
--    학습: 최근 6개월 이전 / 탐지: 최근 6개월 (분리 필수)
-- =========================================================================

-- 2-1. 학습용 뷰 (과거 데이터 — 최근 6개월 제외)
CREATE OR REPLACE VIEW ANALYTICS.V_ANOMALY_TRAIN AS
SELECT
    YEAR_MONTH     AS TS,
    INSTALL_STATE  AS SERIES,
    SUM(CONTRACT_COUNT) AS TARGET
FROM STAGING.STG_REGIONAL
WHERE YEAR_MONTH < DATEADD(MONTH, -6, (SELECT MAX(YEAR_MONTH) FROM STAGING.STG_REGIONAL))
GROUP BY YEAR_MONTH, INSTALL_STATE
HAVING TARGET > 0
ORDER BY INSTALL_STATE, YEAR_MONTH;

-- 2-2. 탐지용 뷰 (최근 6개월 — 학습 기간 이후)
CREATE OR REPLACE VIEW ANALYTICS.V_ANOMALY_DETECT AS
SELECT
    YEAR_MONTH     AS TS,
    INSTALL_STATE  AS SERIES,
    SUM(CONTRACT_COUNT) AS TARGET
FROM STAGING.STG_REGIONAL
WHERE YEAR_MONTH >= DATEADD(MONTH, -6, (SELECT MAX(YEAR_MONTH) FROM STAGING.STG_REGIONAL))
GROUP BY YEAR_MONTH, INSTALL_STATE
HAVING TARGET > 0
ORDER BY INSTALL_STATE, YEAR_MONTH;

-- 2-3. 모델 생성 (과거 CONTRACT_COUNT로 학습)
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ANALYTICS.ANOMALY_CONTRACT_MODEL(
    INPUT_DATA        => TABLE(ANALYTICS.V_ANOMALY_TRAIN),
    SERIES_COLNAME    => 'SERIES',
    TIMESTAMP_COLNAME => 'TS',
    TARGET_COLNAME    => 'TARGET',
    LABEL_COLNAME     => '',
    CONFIG_OBJECT     => {'ON_ERROR': 'SKIP'}
);

-- 2-4. 이상탐지 실행 (최근 데이터에서 이상치 탐지)
DELETE FROM MART.ANOMALY_OUTPUT
WHERE TARGET_METRIC = 'CONTRACT_COUNT';

-- 기존 CVR 이상치도 정리
DELETE FROM MART.ANOMALY_OUTPUT
WHERE TARGET_METRIC = 'OVERALL_CVR';

INSERT INTO MART.ANOMALY_OUTPUT
    (SERIES_KEY, TARGET_METRIC, TS, OBSERVED, EXPECTED, LOWER, UPPER, IS_ANOMALY, ANOMALY_SCORE)
SELECT
    SERIES             AS SERIES_KEY,
    'CONTRACT_COUNT'   AS TARGET_METRIC,
    TS,
    Y                  AS OBSERVED,
    FORECAST           AS EXPECTED,
    LOWER_BOUND        AS LOWER,
    UPPER_BOUND        AS UPPER,
    IS_ANOMALY,
    PERCENTILE         AS ANOMALY_SCORE
FROM TABLE(ANALYTICS.ANOMALY_CONTRACT_MODEL!DETECT_ANOMALIES(
    INPUT_DATA        => TABLE(ANALYTICS.V_ANOMALY_DETECT),
    TIMESTAMP_COLNAME => 'TS',
    TARGET_COLNAME    => 'TARGET',
    SERIES_COLNAME    => 'SERIES',
    CONFIG_OBJECT     => {'prediction_interval': 0.95}
));

-- =========================================================================
-- 3. FORECAST: 시도별 CONTRACT_COUNT 예측 (3개월)
-- =========================================================================

CREATE OR REPLACE VIEW ANALYTICS.V_FORECAST_REGIONAL_INPUT AS
SELECT
    YEAR_MONTH     AS TS,
    INSTALL_STATE  AS SERIES,
    SUM(CONTRACT_COUNT) AS TARGET
FROM STAGING.STG_REGIONAL
WHERE YEAR_MONTH < (SELECT MAX(YEAR_MONTH) FROM STAGING.STG_REGIONAL)
GROUP BY YEAR_MONTH, INSTALL_STATE
HAVING TARGET > 0
ORDER BY INSTALL_STATE, YEAR_MONTH;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ANALYTICS.FORECAST_REGIONAL_MODEL(
    INPUT_DATA      => TABLE(ANALYTICS.V_FORECAST_REGIONAL_INPUT),
    SERIES_COLNAME  => 'SERIES',
    TIMESTAMP_COLNAME => 'TS',
    TARGET_COLNAME  => 'TARGET',
    CONFIG_OBJECT   => {'ON_ERROR': 'SKIP'}
);

DELETE FROM MART.FORECAST_OUTPUT
WHERE SERIES_TYPE = 'STATE' AND TARGET_METRIC = 'CONTRACT_COUNT';

INSERT INTO MART.FORECAST_OUTPUT
    (SERIES_KEY, SERIES_TYPE, TARGET_METRIC, TS, FORECAST, LOWER, UPPER)
SELECT
    SERIES           AS SERIES_KEY,
    'STATE'          AS SERIES_TYPE,
    'CONTRACT_COUNT' AS TARGET_METRIC,
    TS,
    FORECAST,
    LOWER_BOUND      AS LOWER,
    UPPER_BOUND      AS UPPER
FROM TABLE(ANALYTICS.FORECAST_REGIONAL_MODEL!FORECAST(
    FORECASTING_PERIODS => 3,
    CONFIG_OBJECT => {'prediction_interval': 0.95}
));
