-- 06_feature_store.sql
-- ML Feature Store: 카테고리 레벨 합산 (채널 레벨 → 카테고리 레벨로 변경)
-- Grain: CATEGORY × MONTH (이전: CHANNEL × CATEGORY × MONTH)
-- CVR=0 행 제거, 미완성월 제외

USE DATABASE TELECOM_DB;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- ANALYTICS.ML_FEATURE_STORE
-- =========================================================================
CREATE OR REPLACE TABLE ANALYTICS.ML_FEATURE_STORE AS
WITH base AS (
    -- 카테고리 × 월 단위로 합산 (채널 제거)
    SELECT
        YEAR_MONTH,
        MAIN_CATEGORY_NAME AS CATEGORY,
        SUM(CONTRACT_COUNT)  AS CONTRACT_COUNT,
        SUM(PAYEND_COUNT)    AS PAYEND_COUNT,
        SUM(OPEN_COUNT)      AS OPEN_COUNT,
        -- 가중 평균 CVR
        CASE
            WHEN SUM(CONTRACT_COUNT) > 0
            THEN ROUND(SUM(PAYEND_CVR * CONTRACT_COUNT) / SUM(CONTRACT_COUNT), 2)
            ELSE 0
        END AS PAYEND_CVR,
        CASE
            WHEN SUM(CONTRACT_COUNT) > 0
            THEN ROUND(SUM(OPEN_CVR * CONTRACT_COUNT) / SUM(CONTRACT_COUNT), 2)
            ELSE 0
        END AS OPEN_CVR,
        ROUND(AVG(AVG_NET_SALES), 2) AS AVG_NET_SALES,
        -- 채널 다양성 지표
        COUNT(DISTINCT RECEIVE_PATH_NAME) AS N_CHANNELS,
        -- HHI는 별도 계산 (윈도우 함수 내 윈도우 함수 불가)
        0.0 AS CHANNEL_HHI,
        -- 상위 채널 점유율
        MAX(CONTRACT_COUNT) * 1.0 / NULLIF(SUM(CONTRACT_COUNT), 0) AS TOP_CHANNEL_SHARE
    FROM STAGING.STG_CHANNEL
    WHERE YEAR_MONTH < (SELECT MAX(YEAR_MONTH) FROM STAGING.STG_CHANNEL)  -- 미완성월 제외
      AND MAIN_CATEGORY_NAME IN ('인터넷','렌탈','모바일','알뜰 요금제','유심만')  -- 주요 카테고리만
    GROUP BY YEAR_MONTH, MAIN_CATEGORY_NAME
    HAVING SUM(PAYEND_COUNT) > 0  -- CVR=0 제거
       AND SUM(CONTRACT_COUNT) >= 50  -- 최소 볼륨
),
with_lags AS (
    SELECT
        b.*,
        -- Lag 피처 (카테고리 레벨)
        LAG(PAYEND_CVR, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS PAYEND_CVR_LAG1,
        LAG(PAYEND_CVR, 2) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS PAYEND_CVR_LAG2,
        LAG(PAYEND_CVR, 3) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS PAYEND_CVR_LAG3,
        LAG(CONTRACT_COUNT, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS CONTRACT_COUNT_LAG1,
        LAG(CONTRACT_COUNT, 2) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS CONTRACT_COUNT_LAG2,
        LAG(AVG_NET_SALES, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS AVG_NET_SALES_LAG1,
        LAG(OPEN_CVR, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS OPEN_CVR_LAG1,
        LAG(N_CHANNELS, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS N_CHANNELS_LAG1,
        LAG(CHANNEL_HHI, 1) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH) AS HHI_LAG1,
        -- 이동평균
        AVG(PAYEND_CVR) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PAYEND_CVR_MA3,
        AVG(PAYEND_CVR) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS PAYEND_CVR_MA6,
        AVG(CONTRACT_COUNT) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS CONTRACT_MA3,
        -- 표준편차 (변동성)
        STDDEV(PAYEND_CVR) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PAYEND_CVR_STD3,
        -- 카테고리 역사적 평균 (현재행 제외)
        AVG(PAYEND_CVR) OVER (PARTITION BY CATEGORY ORDER BY YEAR_MONTH ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS CATEGORY_HISTORICAL_CVR
    FROM base b
),
-- 퍼널 데이터 교차 피처 (STG_FUNNEL)
funnel_features AS (
    SELECT
        YEAR_MONTH,
        CATEGORY,
        OVERALL_CVR AS FUNNEL_OVERALL_CVR,
        TOTAL_COUNT AS FUNNEL_TOTAL_COUNT,
        PAYEND_COUNT AS FUNNEL_PAYEND_COUNT
    FROM STAGING.STG_FUNNEL
),
with_funnel AS (
    SELECT
        wl.*,
        COALESCE(ff.FUNNEL_OVERALL_CVR, 0) AS FUNNEL_OVERALL_CVR,
        COALESCE(ff.FUNNEL_TOTAL_COUNT, 0) AS FUNNEL_TOTAL_COUNT,
        -- 시간 피처
        MONTH(wl.YEAR_MONTH) AS MONTH_OF_YEAR,
        QUARTER(wl.YEAR_MONTH) AS QUARTER,
        -- 타겟: 다음 달 PAYEND_CVR
        LEAD(PAYEND_CVR, 1) OVER (PARTITION BY wl.CATEGORY ORDER BY wl.YEAR_MONTH) AS NEXT_PAYEND_CVR
    FROM with_lags wl
    LEFT JOIN funnel_features ff
        ON wl.YEAR_MONTH = ff.YEAR_MONTH AND wl.CATEGORY = ff.CATEGORY
),
with_target AS (
    SELECT
        wf.*,
        -- 카테고리별 퍼센타일 기준 타겟
        PERCENTILE_CONT(0.67) WITHIN GROUP (ORDER BY NEXT_PAYEND_CVR)
            OVER (PARTITION BY CATEGORY) AS P67,
        PERCENTILE_CONT(0.33) WITHIN GROUP (ORDER BY NEXT_PAYEND_CVR)
            OVER (PARTITION BY CATEGORY) AS P33
    FROM with_funnel wf
    WHERE NEXT_PAYEND_CVR IS NOT NULL
)
SELECT
    YEAR_MONTH,
    CATEGORY,
    -- 기본 피처
    PAYEND_CVR,
    OPEN_CVR,
    CONTRACT_COUNT,
    AVG_NET_SALES,
    N_CHANNELS,
    ROUND(CHANNEL_HHI, 4) AS CHANNEL_HHI,
    ROUND(TOP_CHANNEL_SHARE, 4) AS TOP_CHANNEL_SHARE,
    -- Lag 피처
    COALESCE(PAYEND_CVR_LAG1, PAYEND_CVR) AS PAYEND_CVR_LAG1,
    COALESCE(PAYEND_CVR_LAG2, PAYEND_CVR) AS PAYEND_CVR_LAG2,
    COALESCE(PAYEND_CVR_LAG3, PAYEND_CVR) AS PAYEND_CVR_LAG3,
    COALESCE(CONTRACT_COUNT_LAG1, CONTRACT_COUNT) AS CONTRACT_COUNT_LAG1,
    COALESCE(CONTRACT_COUNT_LAG2, CONTRACT_COUNT) AS CONTRACT_COUNT_LAG2,
    COALESCE(AVG_NET_SALES_LAG1, AVG_NET_SALES) AS AVG_NET_SALES_LAG1,
    COALESCE(OPEN_CVR_LAG1, OPEN_CVR) AS OPEN_CVR_LAG1,
    COALESCE(N_CHANNELS_LAG1, N_CHANNELS) AS N_CHANNELS_LAG1,
    COALESCE(HHI_LAG1, CHANNEL_HHI) AS HHI_LAG1,
    -- 이동평균 / 변동성
    ROUND(COALESCE(PAYEND_CVR_MA3, PAYEND_CVR), 2) AS PAYEND_CVR_MA3,
    ROUND(COALESCE(PAYEND_CVR_MA6, PAYEND_CVR), 2) AS PAYEND_CVR_MA6,
    ROUND(COALESCE(CONTRACT_MA3, CONTRACT_COUNT), 0) AS CONTRACT_MA3,
    ROUND(COALESCE(PAYEND_CVR_STD3, 0), 4) AS PAYEND_CVR_STD3,
    ROUND(COALESCE(CATEGORY_HISTORICAL_CVR, PAYEND_CVR), 2) AS CATEGORY_HISTORICAL_CVR,
    -- 퍼널 교차 피처
    FUNNEL_OVERALL_CVR,
    FUNNEL_TOTAL_COUNT,
    -- 시간 피처
    MONTH_OF_YEAR,
    QUARTER,
    -- 타겟
    NEXT_PAYEND_CVR,
    CASE
        WHEN NEXT_PAYEND_CVR >= P67 THEN 'HIGH'
        WHEN NEXT_PAYEND_CVR >= P33 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS TARGET_CLASS
FROM with_target;
