-- 07_data_quality.sql
-- Python 기반 데이터 품질 검증 결과 저장 테이블
-- DMF(Enterprise Only) 대신 SQL 쿼리로 품질 체크 수행

USE DATABASE TELECOM_DB;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- 1. 품질 검증 결과 테이블
-- =========================================================================
CREATE TABLE IF NOT EXISTS MART.DATA_QUALITY_RESULTS (
    CHECK_TIME      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    TABLE_NAME      VARCHAR(100),
    COLUMN_NAME     VARCHAR(100),
    CHECK_TYPE      VARCHAR(50),
    VIOLATION_COUNT NUMBER,
    TOTAL_COUNT     NUMBER,
    VIOLATION_PCT   FLOAT,
    QUALITY_STATUS  VARCHAR(20),
    DETAIL          VARCHAR(500)
);

-- =========================================================================
-- 2. 품질 검증 실행 (MERGE로 최신 결과만 유지)
-- =========================================================================
DELETE FROM MART.DATA_QUALITY_RESULTS;

-- 2-1. NULL 검사
INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_FUNNEL', 'OVERALL_CVR', 'NULL_CHECK',
    COUNT_IF(OVERALL_CVR IS NULL), COUNT(*),
    ROUND(COUNT_IF(OVERALL_CVR IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT_IF(OVERALL_CVR IS NULL) = 0 THEN 'PASS' WHEN COUNT_IF(OVERALL_CVR IS NULL) * 100.0 / COUNT(*) < 10 THEN 'WARNING' ELSE 'CRITICAL' END,
    'CVR NULL 검사'
FROM STAGING.STG_FUNNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_CHANNEL', 'AVG_NET_SALES', 'NULL_CHECK',
    COUNT_IF(AVG_NET_SALES IS NULL), COUNT(*),
    ROUND(COUNT_IF(AVG_NET_SALES IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT_IF(AVG_NET_SALES IS NULL) = 0 THEN 'PASS' WHEN COUNT_IF(AVG_NET_SALES IS NULL) * 100.0 / COUNT(*) < 10 THEN 'WARNING' ELSE 'CRITICAL' END,
    '평균매출 NULL 검사'
FROM STAGING.STG_CHANNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_CHANNEL', 'PAYEND_CVR', 'NULL_CHECK',
    COUNT_IF(PAYEND_CVR IS NULL), COUNT(*),
    ROUND(COUNT_IF(PAYEND_CVR IS NULL) * 100.0 / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT_IF(PAYEND_CVR IS NULL) = 0 THEN 'PASS' ELSE 'WARNING' END,
    '납입CVR NULL 검사'
FROM STAGING.STG_CHANNEL;

-- 2-2. CVR 범위 검사 (0~100%)
INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_FUNNEL', 'OVERALL_CVR', 'RANGE_CHECK',
    COUNT_IF(OVERALL_CVR < 0 OR OVERALL_CVR > 100), COUNT(*),
    ROUND(COUNT_IF(OVERALL_CVR < 0 OR OVERALL_CVR > 100) * 100.0 / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT_IF(OVERALL_CVR < 0 OR OVERALL_CVR > 100) = 0 THEN 'PASS' ELSE 'CRITICAL' END,
    'CVR 0~100% 범위 검사'
FROM STAGING.STG_FUNNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_CHANNEL', 'PAYEND_CVR', 'RANGE_CHECK',
    COUNT_IF(PAYEND_CVR < 0 OR PAYEND_CVR > 100), COUNT(*),
    ROUND(COUNT_IF(PAYEND_CVR < 0 OR PAYEND_CVR > 100) * 100.0 / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT_IF(PAYEND_CVR < 0 OR PAYEND_CVR > 100) = 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '납입CVR 0~100% 범위 검사'
FROM STAGING.STG_CHANNEL;

-- 2-3. 미래 날짜 검사
INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_FUNNEL', 'YEAR_MONTH', 'FUTURE_DATE',
    COUNT_IF(YEAR_MONTH > CURRENT_DATE()), COUNT(*), 0,
    CASE WHEN COUNT_IF(YEAR_MONTH > CURRENT_DATE()) = 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '미래 날짜 레코드 검사'
FROM STAGING.STG_FUNNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_CHANNEL', 'YEAR_MONTH', 'FUTURE_DATE',
    COUNT_IF(YEAR_MONTH > CURRENT_DATE()), COUNT(*), 0,
    CASE WHEN COUNT_IF(YEAR_MONTH > CURRENT_DATE()) = 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '미래 날짜 레코드 검사'
FROM STAGING.STG_CHANNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_REGIONAL', 'YEAR_MONTH', 'FUTURE_DATE',
    COUNT_IF(YEAR_MONTH > CURRENT_DATE()), COUNT(*), 0,
    CASE WHEN COUNT_IF(YEAR_MONTH > CURRENT_DATE()) = 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '미래 날짜 레코드 검사'
FROM STAGING.STG_REGIONAL;

-- 2-4. 행 수 검사 (비어있으면 CRITICAL)
INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_FUNNEL', '*', 'ROW_COUNT', 0, COUNT(*), 0,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '테이블 행 수: ' || COUNT(*) || '행'
FROM STAGING.STG_FUNNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_CHANNEL', '*', 'ROW_COUNT', 0, COUNT(*), 0,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '테이블 행 수: ' || COUNT(*) || '행'
FROM STAGING.STG_CHANNEL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_REGIONAL', '*', 'ROW_COUNT', 0, COUNT(*), 0,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '테이블 행 수: ' || COUNT(*) || '행'
FROM STAGING.STG_REGIONAL;

INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'ML_FEATURE_STORE', '*', 'ROW_COUNT', 0, COUNT(*), 0,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'CRITICAL' END,
    '피처 스토어 행 수: ' || COUNT(*) || '행'
FROM ANALYTICS.ML_FEATURE_STORE;

-- 2-5. 중복 검사
INSERT INTO MART.DATA_QUALITY_RESULTS (TABLE_NAME, COLUMN_NAME, CHECK_TYPE, VIOLATION_COUNT, TOTAL_COUNT, VIOLATION_PCT, QUALITY_STATUS, DETAIL)
SELECT 'STG_FUNNEL', 'YEAR_MONTH+CATEGORY', 'DUPLICATE_CHECK',
    COUNT(*) - COUNT(DISTINCT YEAR_MONTH || MAIN_CATEGORY_NAME),
    COUNT(*), 0,
    CASE WHEN COUNT(*) = COUNT(DISTINCT YEAR_MONTH || MAIN_CATEGORY_NAME) THEN 'PASS' ELSE 'WARNING' END,
    '년월+카테고리 중복 검사'
FROM STAGING.STG_FUNNEL;
